.PHONY: clean All

All:
	@echo "----------Building project:[ VirtualFunction - Debug ]----------"
	@cd "VirtualFunction" && "$(MAKE)" -f  "VirtualFunction.mk"
clean:
	@echo "----------Cleaning project:[ VirtualFunction - Debug ]----------"
	@cd "VirtualFunction" && "$(MAKE)" -f  "VirtualFunction.mk" clean
