.PHONY: clean All

All:
	@echo "----------Building project:[ ChallangeSection - Debug ]----------"
	@cd "ChallangeSection" && "$(MAKE)" -f  "ChallangeSection.mk"
clean:
	@echo "----------Cleaning project:[ ChallangeSection - Debug ]----------"
	@cd "ChallangeSection" && "$(MAKE)" -f  "ChallangeSection.mk" clean
