.PHONY: clean All

All:
	@echo "----------Building project:[ Test_QAVerify - Debug ]----------"
	@cd "C:\Users\NDA\Desktop\CPPExamples\Test_QAVerify" && "$(MAKE)" -f  "Test_QAVerify.mk"
clean:
	@echo "----------Cleaning project:[ Test_QAVerify - Debug ]----------"
	@cd "C:\Users\NDA\Desktop\CPPExamples\Test_QAVerify" && "$(MAKE)" -f  "Test_QAVerify.mk" clean
